import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import type { PropsWithChildren } from 'react'

import clsx from 'clsx'

import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import { ThemeProvider } from '@/components/theme-provider'

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  fallback: ['sans-serif'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={clsx(roboto.className, 'scroll-smooth antialiased')}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Header />
          <main className="mx-auto min-h-screen max-w-7xl py-32">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
