import { Header } from "@/components/header";
import "./globals.css";
import clsx from "clsx";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import type { PropsWithChildren } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import { Footer } from "@/components/footer";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  fallback: ["sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={clsx(roboto.className, "antialiased scroll-smooth")}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Header />
          <main className="py-32 mx-auto max-w-7xl min-h-screen">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
